### PR TITLE
removing css imports and adding fonts into dist

### PR DESCRIPTION
**Pull request by jivewise**
screen shot 2015-01-29 at 1 16 09 am

### CODE REVIEW

**Comment by philschatz** [comment]
From the screenshot It looks like only the font-awesome icons loaded. there should be a + in the red circle.

**Comment by philschatz** [comment]
Are the katex font files loaded in? and did the updates to the local testing load both sets of fonts?

**Comment by jivewise** [comment]
Yes, the katex files are in there as well, and both fonts are showing up.
screen shot 2015-01-29 at 7 13 34 am

**Comment by philschatz** [comment]
Thanks!

**Pull request merged**
