### PR TITLE
Image upload for exercises

### PR DESCRIPTION
**Pull request by nathanstitt**
Goes along with: https://github.com/openstax/exercises/pull/103

screen shot 2016-02-23 at 6 33 13 pm

### CODE REVIEW

**Comment by philschatz** [comment]
I'm not sure how useful it is to show the image on the left-hand-side. Also, in order to be able to put the uploaded image anywhere (like between 2 paragraphs, or inside a list) I think the result of uploading should be a textbox that has `` with the text selected.

I'm just trying to suggest the quickest way of uploading images internally. Thoughts?

**Comment by nathanstitt** [comment]
@philschatz the image you're seeing is a preview.  It's displayed as-is until it's uploaded and then has the markdown input for copy & paste.  I've updated the screenshot to hopefully make it more clear.  I do think it's fairly important to show the image somewhere though, so the user can be sure they've selected the proper image.  If we don't I think they'll be forced to create multiple copies of the same exercise just to fix bad image uploads.

**Comment by nathanstitt** [comment]
I've marked this ready for review, but we may need to do a follow-up it depending on how the redux stuff works out.

**Comment by philschatz** [comment]
I think the exercise editor edits HTML, not markdown right? And wouldn't the user see the image when they preview? (but a pre-upload preview seems ok to me)

**Comment by jpslav** [comment]
FWIW @philschatz, tho we had talked about hiding the attachments list in the exercise JSON, I'm planning on having it there only for users who can see the solutions.

**Comment by philschatz** [comment]
:+1: Yep, I think we just didn't want a solution image to accidentally leak out (correct me if I'm wrong)

**Comment by jpslav** [comment]
Yes exactly

**Comment by nathanstitt** [comment]
This is going to need a bit more work.  It now turns out that it should support multiple images and also deal with non-image assets.

**Comment by philschatz** [comment]
I'm a bit confused about the screenshot; why does each `<textarea>` have multiple `` tags in it?

**Comment by nathanstitt** [comment]
Those are the different sizes.  When the BE processes the image it creates a large, medium, and small version.  So I'm listing the URL's for the original and each of the sizes.  Maybe I should only list one size?

**Comment by philschatz** [comment]
oh, I see. I think that would be confusing to the DMS's. maybe just the large one? (as long as there are enough bits to reconstruct). @Dantemss which image size does the spreadsheet importer use?

**Comment by Dantemss** [comment]
Only the large one is currently linked. (is there a way to make a link that changes based on the device size? :) )

**Comment by philschatz** [comment]
There is a way to do it but I think we would need to wrap every `` in a `<span>` which contains 3 `` tags and then hide all but the correct one. I'm not sure if the browser will fetch all 3 though.

Or maybe have the small in `src=` and the rest in `data-src-large=""` or something and JS would replace it

Or, any other ideas?

**Comment by nathanstitt** [comment]
if we're only going to include a link to one size, then it seems like It'd be best to include the original.  That way the uploader will get the size they expect.  

Otherwise you'll have people upload small images and be confused when they are blown up and vice-versa.

**Comment by jivewise** [comment]
This looks good to me :+1:

**Comment by philschatz** [comment]
What happens if a person (or 2 different people) uploads an image to an exercise, and then accidentally uploads the same image to another exercise and then delete's it? 

Would the 1st exercise still work?

**Comment by nathanstitt** [comment]
Yes, each upload is tied to a specific exercise and version.  So they don't share storage and it's safe to delete them independently.

**Comment by philschatz** [comment]
Oh, that seems to destroy the utility of having the hash in the URL. But thanks!

**Pull request merged**
