### PR TITLE
extract SuretyGuard to shared components

### PR DESCRIPTION
**Pull request by nathanstitt**
into https://github.com/openstax/react-components/pull/72

### CODE REVIEW

**Comment by philschatz** [comment]
This has failing tests. I re-ran them but they still failed ; (

**Comment by nathanstitt** [comment]
Yeah, that's what I get for rushing through the PR and not running specs locally, I missed a `require` :(

Thanks for checking it

**Comment by jivewise** [comment]
:+1: Sweet, I think we need to use the surety guard on the HW builder changes, thanks for doing this!

**Comment by nathanstitt** [comment]
Hehe, That's actually what I extracted it for.  I replaced a `confirm` in HW builder with it.  There's probably other spots that could use it as well

**Pull request merged**
