### PR TITLE
Fixed bugs with tagging dropdowns and textarea

### PR DESCRIPTION
**Pull request by jivewise**
This fixes a bug where changing the editable bugs clears out changes to the fixed drop down tags.

### CODE REVIEW

**Comment by nathanstitt** [comment]
This all looks good, but I think i've uncovered an additional bug that might be good to put on this PR since it's already bug fixes.

If you load exercises without an ID on the url, like from https://exercises-dev.openstax.org/exercises 

It pops up a query box that asks for an id and stores it on `@state`. But then quite a few places attempt to access the ID from  `@props.id`  I hit the bug at: https://github.com/openstax/exercises-js/blob/master/src/components/exercise.cjsx#L53 but it looks like there's other spots also.

If they were changed to use the `getId()` method then I think they'd work.  Does that make sense?

**Comment by nathanstitt** [comment]
Setting back to work-in-progress while @jivewise works on the `@props.id` bug

**Comment by nathanstitt** [comment]
@jivewise is this complete?  Looks like you've squashed the `@props.id` bugs at least.

**Comment by jivewise** [comment]
yep, should be done

**Comment by nathanstitt** [comment]
Looks good @jivewise - tested on https://exercises-dev.openstax.org/exercises/1 and works fine.

**Pull request merged**
